MODEL: #MODEL field
    framework: "RecognizerTransformer" #Mandatory, indicate the type of network, associate to the 'paddlevideo/modeling/framework/' .
    backbone: #Mandatory, indicate the type of backbone, associate to the 'paddlevideo/modeling/backbones/' .
        name: "VisionTransformer_tweaks" #Mandatory, The name of backbone.
#        pretrained: "data/vit_base_patch16_224_miil_21k_trans.pdparams" #Optional, pretrained model path.
        pretrained: "" #Optional, pretrained model path.
        img_size: 224
        patch_size: 16
        in_channels: 3
        embed_dim: 768
        depth: 12
        num_heads: 12
        mlp_ratio: 4
        qkv_bias: False
        epsilon: 1e-6
#        num_seg: 8
        num_seg: 3
        attention_type: 'divided_space_time'
    head:
        name: "ppTimeSformerHead" #Mandatory, indicate the type of head, associate to the 'paddlevideo/modeling/heads'
        num_classes: 5 #Optional, the number of classes to be classified.
        in_channels: 768 #input channel of the extracted feature.
        std: 0.02 #std value in params initialization
        ls_eps: 0.1
#    runtime_cfg: # configuration used when the model is train or test.
#        test: # test config
##            num_seg: 8
#            num_seg: 3
#            avg_type: 'prob' # 'score' or 'prob'

DATASET: #DATASET field
#    batch_size: 2  #Mandatory, bacth size
    batch_size: 4  #Mandatory, bacth size
    num_workers: 0  #Mandatory, XXX the number of subprocess on each GPU.
    test_batch_size: 1 #Mandatory, test bacth size
    train:
        format: "FrameDataset" #Mandatory, indicate the type of dataset, associate to the 'paddlevidel/loader/dateset'
        data_prefix: "" #Mandatory, train data root path
        file_path: "/media/dp504/36675aac-be99-45b0-abf0-9c74c037c1b7/PycharmProjects/swf/datasset/dataset_last/task_VideoClassfy_frames/task_VideoClassfy_frames_train_list.txt"
        suffix: 'img_{:05}.jpg'
    valid:
        format: "FrameDataset" #Mandatory, indicate the type of dataset, associate to the 'paddlevidel/loader/dateset'
        data_prefix: "" #Mandatory, valid data root path
        file_path: "/media/dp504/36675aac-be99-45b0-abf0-9c74c037c1b7/PycharmProjects/swf/datasset/dataset_last/task_VideoClassfy_frames/task_VideoClassfy_frames_val_list.txt"
        suffix: 'img_{:05}.jpg'
    test:
        format: "FrameDataset" #Mandatory, indicate the type of dataset, associate to the 'paddlevidel/loader/dateset'
        data_prefix: "" #Mandatory, valid data root path
        file_path: "/media/dp504/36675aac-be99-45b0-abf0-9c74c037c1b7/PycharmProjects/swf/datasset/dataset_last/task_VideoClassfy_frames/task_VideoClassfy_frames_val_list.txt"
        suffix: 'img_{:05}.jpg'

PIPELINE: #PIPELINE field
    train: #Mandotary, indicate the pipeline to deal with the training data, associate to the 'paddlevideo/loader/pipelines/'
        decode:
            name: "FrameDecoder"
        sample:
            name: "Sampler"
#            num_seg: 8
            num_seg: 3
            seg_len: 1
            valid_mode: False
            dense_sample: True
        transform: #Mandotary, image transfrom operator
            - Scale:
                short_size: 224
            - MultiScaleCrop:
                target_size: 224
            - RandomCrop:
                target_size: 224
            - RandomFlip:
            - Image2Array:
            - Normalization:
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
    valid: #Mandatory, indicate the pipeline to deal with the validing data. associate to the 'paddlevideo/loader/pipelines/'
        decode:
            name: "FrameDecoder"
        sample:
            name: "Sampler"
#            num_seg: 8
            num_seg: 3
            seg_len: 1
            valid_mode: True
        transform:
            - Scale:
                short_size: 224
            - CenterCrop:
                target_size: 224
            - Image2Array:
            - Normalization:
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
    test:
        decode:
            name: "FrameDecoder"
        sample:
            name: "Sampler"
#            num_seg: 8
            num_seg: 3
            seg_len: 1
            valid_mode: True
            dense_sample: True
        transform:
            - Scale:
                short_size: 224
            - GroupFullResSample:
                crop_size: 224
            - Image2Array:
            - Normalization:
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]

OPTIMIZER: #OPTIMIZER field
    name: 'Momentum'
    momentum: 0.9
    learning_rate:
        iter_step: True
        name: 'CustomWarmupCosineDecay'
        max_epoch: 20
        warmup_epochs: 2
        warmup_start_lr: 0.00025
        cosine_base_lr: 0.0025
    weight_decay:
        name: 'L2'
        value: 0.00007
    use_nesterov: True
    grad_clip:
        name: 'ClipGradByGlobalNorm'
        value: 40.0

#GRADIENT_ACCUMULATION:
#    global_batch_size: 64 # Specify the sum of batches to be calculated by all GPUs

MIX:
    name: "VideoMix"
    cutmix_prob: 0.5
    mixup_alpha: 0.2
    cutmix_alpha: 1.0

METRIC:
    name: 'CenterCropMetric'

INFERENCE:
    name: 'TimeSformer_Inference_helper'
#    num_seg: 8
    num_seg: 3
    target_size: 224
    mean: [0, 0, 0]
    std: [1, 1, 1]

model_name: "ppTimeSformer_task_VideoClassfy_frames_no_pretrained"
log_interval: 1 #Optional, the interal of logger, default:10
save_interval: 1
#epochs: 20 #Mandatory, total epoch
epochs: 80 #Mandatory, total epoch
log_level: "INFO" #Optional, the logger level. default: "INFO"
