MODEL: #MODEL field
    framework: "Recognizer2D" #Mandatory, indicate the type of network, associate to the 'paddlevideo/modeling/framework/' .
    backbone: #Mandatory, indicate the type of backbone, associate to the 'paddlevideo/modeling/backbones/' .
        name: "ResNetTweaksTSN" #Mandatory, The name of backbone.
#        pretrained: "data/ResNet50_vd_ssld_v2_pretrained.pdparams" #Optional, pretrained model path.
        pretrained: ""
        layers: 50 #Optional, the depth of backbone architecture.
    head:
        name: "ppTSNHead" #Mandatory, indicate the type of head, associate to the 'paddlevideo/modeling/heads'
        num_classes: 5 #Optional, the number of classes to be classified.
        in_channels: 2048 #input channel of the extracted feature.
        drop_ratio: 0.4 #the ratio of dropout
        std: 0.01 #std value in params initialization
        ls_eps: 0.1


DATASET: #DATASET field
    batch_size: 4 #Mandatory, bacth size
    valid_batch_size: 4
    test_batch_size: 1
    num_workers: 0 #Mandatory, XXX the number of subprocess on each GPU.
    train:
        format: "FrameDataset" #Mandatory, indicate the type of dataset, associate to the 'paddlevidel/loader/dateset'
        data_prefix: "" #Mandatory, train data root path
        file_path: "/media/dp504/36675aac-be99-45b0-abf0-9c74c037c1b7/PycharmProjects/swf/datasset/dataset_last/task_VideoClassfy_frames/task_VideoClassfy_frames_train_list.txt"
        suffix: 'img_{:05}.jpg'
    valid:
        format: "FrameDataset" #Mandatory, indicate the type of dataset, associate to the 'paddlevidel/loader/dateset'
        data_prefix: "" #Mandatory, valid data root path
        file_path: "/media/dp504/36675aac-be99-45b0-abf0-9c74c037c1b7/PycharmProjects/swf/datasset/dataset_last/task_VideoClassfy_frames/task_VideoClassfy_frames_val_list.txt"
        suffix: 'img_{:05}.jpg'
    test:
        format: "FrameDataset" #Mandatory, indicate the type of dataset, associate to the 'paddlevidel/loader/dateset'
        data_prefix: "" #Mandatory, valid data root path
        file_path: "/media/dp504/36675aac-be99-45b0-abf0-9c74c037c1b7/PycharmProjects/swf/datasset/dataset_last/task_VideoClassfy_frames/task_VideoClassfy_frames_val_list.txt"
        suffix: 'img_{:05}.jpg'


PIPELINE: #PIPELINE field
    train: #Mandotary, indicate the pipeline to deal with the training data, associate to the 'paddlevideo/loader/pipelines/'
        decode:
            name: "FrameDecoder"
        sample:
            name: "Sampler"
            num_seg: 3
            seg_len: 1
            valid_mode: False
            select_left: True
        transform: #Mandotary, image transfrom operator
            - Scale:
                short_size: 256
                fixed_ratio: False
                do_round: True
                backend: 'cv2'
            - MultiScaleCrop:
                target_size: 224
                allow_duplication: True
                more_fix_crop: True
                backend: 'cv2'
            - RandomFlip:
            - Image2Array:
            - Normalization:
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]

    valid: #Mandatory, indicate the pipeline to deal with the validing data. associate to the 'paddlevideo/loader/pipelines/'
        decode:
            name: "FrameDecoder"
        sample:
            name: "Sampler"
            num_seg: 3
            seg_len: 1
            valid_mode: True
            select_left: True
        transform:
            - Scale:
                short_size: 256
                fixed_ratio: False
                do_round: True
                backend: 'cv2'
            - CenterCrop:
                target_size: 224
                do_round: False
            - Image2Array:
            - Normalization:
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]

    test:
        decode:
            name: "FrameDecoder"
        sample:
            name: "Sampler"
            num_seg: 25
            seg_len: 1
            valid_mode: True
            select_left: True
        transform:
            - Scale:
                short_size: 256
                fixed_ratio: False
                do_round: True
                backend: 'cv2'
            - TenCrop:
                target_size: 224
            - Image2Array:
            - Normalization:
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]


OPTIMIZER: #OPTIMIZER field
    name: 'Momentum' #Mandatory, the type of optimizer, associate to the 'paddlevideo/solver/'
    momentum: 0.9
    learning_rate: #Mandatory, the type of learning rate scheduler, associate to the 'paddlevideo/solver/'
        iter_step: True
        name: 'CustomWarmupCosineDecay'
        max_epoch: 100
        warmup_epochs: 10
        warmup_start_lr: 0.005
        cosine_base_lr: 0.01
    weight_decay:
        name: 'L2'
        value: 0.0001
    use_nesterov: True


MIX:
    name: "Mixup"
    alpha: 0.2


METRIC:
    name: 'CenterCropMetric'


INFERENCE:
    name: 'ppTSN_Inference_helper'
    num_seg: 25
    target_size: 224


model_name: "ppTSN_task_VideoClassfy_frames_no_pretrained"
log_interval: 1 #Optional, the interal of logger, default:10
save_interval: 1
val_interval: 1
epochs: 100 #Mandatory, total epoch
log_level: "INFO" #Optional, the logger level. default: "INFO"
